name: hpf_cli
description: the dart cli support the user create the flutter application follow clean architecture. Presentattion layer use Provider state management.
version: 1.0.0+5
homepage: https://github.com/dohoan259/hpf

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  path: ^1.8.0
  meta: ">=1.7.0 <2.0.0"
  recase: ">=4.0.0 <5.0.0"
  ansicolor: ">=2.0.1 <3.0.0"
  process_run: ">=0.12.2 <1.0.0"
  http: ">=0.13.4 <2.0.0"
  version: ">=2.0.0 <3.0.0"
  intl: ">=0.17.0 <1.0.0"
  cli_dialog: ">=0.5.0 <1.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  yaml: ">=3.1.0 <4.0.0"
  collection: ">=1.15.0 <2.0.0"
  pubspec: ">=2.0.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  hpf: hpf_cli
